name: "Release Devsonic Project"
on:
  push:
    branches:
      - master
jobs:
  
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      
      - name: "Getting source code"
        uses: actions/checkout@v5
      
      - name: "Installing Node.JS v22.20"
        uses: actions/setup-node@v4
        with:
          node-version: '22.20'
      
      - name: "Installing project dependencies"
        run: npm i
      
      - name: "Creating dist"
        run: npm run build

      - name: "Extracting version from package.json"
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: "Uploading dist for the next job"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
  
  publish-to-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: "Getting source code"
        uses: actions/checkout@v5
      
      - name: "Downloading dist"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      
      - name: "Login into DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: "Setting up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      
      - name: "Building and pushing Docker Image"
        run: |
          docker buildx build \
          --push --platform linux/amd64,linux/arm64 \
          --cache-from=type=gha --cache-to=type=gha,mode=max \
          -t ${{ secrets.DOCKER_USERNAME }}/react-app:${{ needs.build.outputs.version }} .
